[package]
name = "judas-rs"
version = "0.1.0"
edition = "2024"
authors = ["Eytan Levy <eytanlevy@proton.me>", "Yaël Pajot <yael.pajot@outlook.fr>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
